---
- name: Lesson 00 - The Development Environment
  hosts: localhost
  tasks:
    - name: Install required packages.
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
